<?php
namespace Swooless\Protocol\Demo;

/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

interface ServerIf
{
    /**
     * @return string
     */
    public function version();
    /**
     * @param \Swooless\Protocol\Demo\User $user
     * @return bool
     */
    public function add(\Swooless\Protocol\Demo\User $user);
    /**
     * @param string $name
     * @return \Swooless\Protocol\Demo\User
     * @throws \Swooless\Protocol\Demo\NotFoundException
     * @throws \Swooless\Protocol\Demo\NotUniqueException
     */
    public function get($name);
}
