/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.swoole.protocol.demo;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class demoConstants {

  public static final java.lang.String SERVER_NAME = "swoole.protocol.demo";

}
